language: android

sudo: false

jdk:
  - oraclejdk8

notifications:
  email: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

cache:
  directories:
    - $HOME/.m2
